<?php
/*
Chatstack - https://www.chatstack.com
Copyright - All Rights Reserved - Stardevelop Pty Ltd

You may not distribute this program in any manner,
modified or otherwise, without the express, written
consent from Stardevelop Pty Ltd (https://www.chatstack.com)

You may make modifications, but only for your own
use and within the confines of the License Agreement.
All rights reserved.

Selling the code for this program without prior
written consent is expressly forbidden. Obtain
permission before redistributing this program over
the Internet or in any other medium.  In all cases
copyright and header must remain intact.

Please Note: You are NOT permitted to modify the stardevelop.com copyright/version lines.

Language codes and locale directories confirm to the ISO639 two letter standard.
Please consult the Live Help Language Setting options for the appropriate code.

Please forward your translated file and appropriate directories to development@stardevelop.com
if you would like your translation to be included in the Live Help download, this allows other
users to use your translation.  Thank you for supporting our Live Help software.

You are permitted to modify the language file from below this point as appropriate.


*/


/*
Uncomment for RTL (Right-to-Left Direction)
$_SETTINGS['DIRECTION'] = 'rtl';
*/


$_LOCALE['chattranscript'] = 'Chat Transcript';

$_LOCALE['welcome'] = 'Welcome! Please continue to start chatting.';
$_LOCALE['enterguestdetails'] = 'Please enter your details below to continue.';
$_LOCALE['elsesendmessage'] = 'Alternatively you can email our staff by sending an';
$_LOCALE['offlinemessage'] = 'Offline Message';
$_LOCALE['continue'] = 'Continue';

$_LOCALE['logout'] = 'Logout';

$_LOCALE['name'] = 'Name';
$_LOCALE['email'] = 'Email';
$_LOCALE['department'] = 'Department';

$_LOCALE['thankyoupatience'] = 'Please wait, connecting you with one of our team members now.';
$_LOCALE['currently'] = 'Currently';
$_LOCALE['userswaiting'] = 'users waiting to chat';
$_LOCALE['refresh'] = 'Refresh';
$_LOCALE['continuewaiting'] = 'Would you like to continue waiting or leave an';
$_LOCALE['offlineemail'] = 'Offline Email';
$_LOCALE['nowchattingwith'] = 'You are now chatting with';
$_LOCALE['joinedconversation'] = 'has joined the conversation.';
$_LOCALE['unfortunatelyoffline'] = 'Unfortunately, our staff are currently unavailable.';
$_LOCALE['filldetailsbelow'] = 'If you would like to contact us, please fill in your details below';
$_LOCALE['leavemsg'] = 'Leave a Message';
$_LOCALE['message'] = 'Message';
$_LOCALE['securitycode'] = 'Security Code';
$_LOCALE['thankyouenquiry'] = 'Thank you for your message, it’s important to us. We will contact you shortly with a response.';
$_LOCALE['addsmilie'] = 'Add Smilie';
$_LOCALE['sendmsg'] = 'Send Message';
$_LOCALE['sendcopy'] = 'Send a copy of this message to your email address';
$_LOCALE['invalidemail'] = 'Invalid Email Address.';
$_LOCALE['invalidsecurityerror'] = 'Invalid Security Code.';
$_LOCALE['invaliddetailserror'] = 'Please complete all details below.';
$_LOCALE['emptyuserdetails'] = 'Please enter your name and email address.';

$_LOCALE['good'] = 'Good';
$_LOCALE['poor'] = 'Poor';
$_LOCALE['neutral'] = 'Neutral';

$_LOCALE['closedusermessage'] = 'Chat Closed';
$_LOCALE['ignoreusermessage'] = 'Your request for support has been declined by our staff, please close the window.  You are not authorised to request another chat at the moment.';

$_LOCALE['alsosendmessage'] = 'Feel free to email us if you are unable to access the chat';
$_LOCALE['cookieserror'] = 'Please Enable Cookies';
$_LOCALE['cookiesenable'] = 'You will need to enable cookies to chat with us.';
$_LOCALE['cookieselse'] = 'If you have cookies enabled within your browser please email support as there is an issue with our live chat software.';

$_LOCALE['question'] = 'Question';
$_LOCALE['enterdetailscallback'] = 'Please enter your details and you will receive a telephone call ASAP.  Thank you.';
$_LOCALE['telephone'] = 'Telephone';
$_LOCALE['country'] = 'Country';
$_LOCALE['connectionerror'] = 'The operator is experiencing connection issues and will return shortly.  We apologise for keeping you waiting.';

$_LOCALE['says'] = 'says';
$_LOCALE['endedchat'] = 'You have ended the chat session, please restart the chat request if you have further questions.';
$_LOCALE['restartchat'] = 'Restart Chat';
$_LOCALE['sentfile'] = 'You have been sent a file.';
$_LOCALE['startdownloading'] = 'Start Downloading';
$_LOCALE['rightclicksave'] = 'or right-click to save the file.';
$_LOCALE['pushedurl'] = 'You have been PUSHed a URL';
$_LOCALE['opennewwindow'] = 'to open a new window.';
$_LOCALE['autogenerated'] = 'Auto Generated';
$_LOCALE['ratedchat'] = '%s has rated the chat session %s';

$_LOCALE['disconnecttitle'] = 'Are you sure that you wish to disconnect?';
$_LOCALE['disconnectdescription'] = 'Disconnecting will close the current chat session.  You can request a new chat from the Online / Offline chat button if you have further questions at a later time.';
$_LOCALE['emailchat'] = 'Email Chat';
$_LOCALE['togglesound'] = 'Toggle Sound';
$_LOCALE['feedback'] = 'Feedback';
$_LOCALE['disconnect'] = 'Disconnect';
$_LOCALE['collapse'] = 'Collapse';
$_LOCALE['expand'] = 'Expand';
$_LOCALE['send'] = 'Send';
$_LOCALE['enteryourmessage'] = 'Type your message and press Enter to send';
$_LOCALE['switchpopupwindow'] = 'Switch to Popup Window';

$_LOCALE['rateyourexperience'] = 'Please rate your customer service experience';
$_LOCALE['thankyoumessagesent'] = 'Thanks for your message, we\'ll get back to you as soon as possible.';
$_LOCALE['close'] = 'Close';
$_LOCALE['featuredisabled'] = 'This feature has been disabled, please contact us via. email.  Thank you.';
$_LOCALE['sorryofflineemail'] = 'Send us a message';
$_LOCALE['cancel'] = 'Cancel';
$_LOCALE['pleasewait'] = 'Please wait';
$_LOCALE['telephonecallshortly'] = 'You will receive a telephone call shortly.';
$_LOCALE['telephonethankyoupatience'] = 'Thank you for your patience.';

$_LOCALE['connect'] = 'Connect';
$_LOCALE['connecting'] = 'Connecting';
$_LOCALE['closechat'] = 'Close Chat';
$_LOCALE['chatsessionblocked'] = 'Your chat session has been blocked by the customer representative.';
$_LOCALE['accessdenied'] = 'Access Denied';
$_LOCALE['blockedchatsession'] = 'Blocked Chat Session';

$_LOCALE['istyping'] = 'is typing';
$_LOCALE['online'] = 'Live Chat';
$_LOCALE['offline'] = 'Offline';
$_LOCALE['brb'] = 'Be Right Back';
$_LOCALE['away'] = 'Away';

$_LOCALE['offlineerrortitle'] = 'Sorry, something went wrong!';
$_LOCALE['offlineerrordescription'] = 'Your message was unable to be sent.  Please contact us directly via. email at';

$_LOCALE['contactus'] = 'Contact Us';

$_LOCALE['password'] = 'Password';
$_LOCALE['retypepassword'] = 'Retype Password';
$_LOCALE['chatwith'] = 'Chat with';

$_LOCALE['introduction'] = 'Hey there! How are you today?';
$_LOCALE['appname'] = 'Live Chat';

$_LOCALE['departments']['Sales'] = 'Sales';
$_LOCALE['departments']['Support'] = 'Support';
$_LOCALE['departments']['General'] = 'General';
$_LOCALE['departments']['Billing'] = 'Billing';
$_LOCALE['departments']['Administrator'] = 'Administrator';

$_LOCALE['feedbackintroduction'] = 'We\'d like some feedback';
$_LOCALE['enteryourfeedbackemail'] = 'Email Address (optional)';
$_LOCALE['enteryourfeedback'] = 'Type your feedback and press Enter';
$_LOCALE['needsupport'] = 'Need Support?';
$_LOCALE['clickhere'] = 'Click Here';

$_LOCALE['chattingwith'] = 'Chatting with';

$_LOCALE['offlinemessagedescription'] = 'Hi there! We\'d love to help you! Leave us a message and we\'ll get back to you as soon as possible.';
$_LOCALE['enteryourofflinename'] = 'Name';
$_LOCALE['enteryourofflineemail'] = 'Email Address';
$_LOCALE['enteryourofflinemessage'] = 'Type your message';

$_LOCALE['retry'] = 'Retry';

?>
